import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "design-system-zeroz/src/app/styles.scss";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import React from "react";
import LayoutPage from "@/app/(protected)/_components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finanças",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="pt-br" data-company="whitelabel">
        <body className={inter.className}>
          <LayoutPage>{children}</LayoutPage>
        </body>
      </html>
    </SessionProvider>
  );
}
